### ISSUE TITLE
Possibly missing registry entry?

### ISSUE THREAD

**Issue by miguelmartins1987** [ericwj/PsSecDrv#12]
The guide, as per https://github.com/ericwj/PsSecDrv/blob/master/README.md , states that it is necessary to, and I quote, "Install a game that brings (a recent version of) SECDRV.sys".

I don't think that's necessarily the case. In fact, I followed said guide from the third step ("Install the Windows 10 SDK from...") to the end, and what I got instead was that the Secdrv service didn't seem to exist ("The specified service does not exist as an installed service") when running `sc.exe qc secdrv`. However, an easy fix for this is to import the following registry file once that happens:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Secdrv]
"Type"=dword:00000001
"Start"=dword:00000002
"ErrorControl"=dword:00000001
"ImagePath"=hex(2):5c,00,3f,00,3f,00,5c,00,43,00,3a,00,5c,00,57,00,69,00,6e,00,\
  64,00,6f,00,77,00,73,00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,\
  00,5c,00,64,00,72,00,69,00,76,00,65,00,72,00,73,00,5c,00,53,00,45,00,43,00,\
  44,00,52,00,56,00,2e,00,53,00,59,00,53,00,00,00
"DisplayName"="Secdrv"
```

...and reboot the system (yes, you **must** reboot!). I tested this on a Windows 10 virtual machine and, after rebooting, it seems to work; querying secdrv now produces positive results; I am now able to run Command & Conquer: Red Alert 2's setup without issues.

Am I missing something here?

Either way, thank you for the guide.

**Comment by mirh** [comment]
I didn't think game redistributed the driver either? Like.. at least since XP [SP2](https://www.computerworld.com/article/1566926/hackers-exploiting-bug-in-drm-shipped-with-windows.html) it ships with windows?

**Comment by ericwj** [comment]
> I didn't think game redistributed the driver either?

Those games do though. They should update to a version they can handle even if the driver would be inbox. Akin to what they do with DirectX: always run the installer to install or update. Actually back then many games would ask to do that for DirectX. But that's silly.

> Am I missing something here?

Probably not. It doesn't really matter how it gets installed. So it can be done through a registry import or through an `sc create` command. But since you are going to play that game requiring it, which runs installation steps for it, the guide is simpler and there are fewer opportunities for mistakes.

> `"ImagePath"=hex(2)`

This is silly. It should be a string, if only for human verification. The ones I checked for being curious use `REG_EXPAND_SZ` instead of hex. Its just defensive coding that hex works, since the bytes correspond.
