### ISSUE TITLE
How to generate and use a self-signed certificate

### ISSUE THREAD

**Issue by 7485** [ericwj/PsSecDrv#2]
Hello,

Some commands don't work, so I searched a solution on internet, but it's difficult to understand how to fix the problem because I don't know how to use Powershell.

When I type : 
`makecert -r -sr LocalMachine -ss My -n $Subject`
it shows : 
`Error: Can't create the key of the subject ('JoeSoft')
Failed`

When I type : 
`signtool sign /sm /s Root /sha1 "$($Publisher.Thumbprint)" /t "http://www.aloaha.com/wi-software-en/aloaha-timestamping-server.php" secdrv
.cat`
It shows : 
`SignTool Error: Invalid SHA1 hash format: /t`

Could you help me please ?

**Comment by ericwj** [comment]
`$Subject` must be an X509 distinguished name using at the bare minimum `"CN=JoeSoft"` or just change the command to read

    makecert -r -sr LocalMachine -ss My -n "CN=$Subject"

`signtool` expects a 20-byte (40-character) hexadecimal string in the `/sha1` argument which matches the SHA1 thumbprint of a certificate in `Cert:\LocalMachine\Root` store (due to the /sm /s Root arguments). Just verify that `$Publisher` is a valid certificate by writing any or all of

    Write-Host $Publisher
    Write-Host ($Publisher -eq $null)
    Write-Host $Publisher.Thumbprint

at the PowerShell prompt. Most likely in this case `$Publisher` is `$null` because the `makecert` command failed.

Also note that you create the certificate with `makecert (...) -ss My` (which you can't change or you'll get another error) and then try to use it from `signtool (...) /s Root`. So in between these commands you will have to copy the certificate from `Cert:\LocalMachine\My` (Personal in `certlm.msc`) to `Cert:\LocalMachine\Root` (Trusted Root Certification Authorities).

You cannot use copy from PowerShell. Do it by hand starting `certlm.msc` first (right-click copy/paste), or export with `Export-PfxCertificate` and then import with `Import-PfxCertificate`. Search the Internet and/or execute e.g. `Get-Help Export-PfxCertificate` to learn how that works.

**Comment by ericwj** [comment]
I recommend further that you don't roll your own time stamping server if you have these kinds of questions. Use the verisign timestamping server I documented (copied from Microsoft documentation):

    signtool sign /sm /s Root /sha1 "$($Publisher.Thumbprint)" /t "http://timestamp.verisign.com/scripts/timstamp.dll" secdrv.cat

Also note that you have a space between secdrv and .cat in the command you posted in the question. That is obviously wrong.

For a complete walkthrough refer to my post on this forum [
SECDRV.SYS Not Loading in Windows 10; this will break thousands of older games.](https://answers.microsoft.com/en-us/windows/forum/games_windows_10/secdrvsys-not-loading-in-windows-10-this-will/65a6fe83-08df-4760-b2ad-6b1ce61d40d4?messageId=3a0323ae-92ea-469c-8a6a-52620e8edca5) page 23, look for a post with some lines on a black background.
