### ISSUE TITLE
"A certificate was explicitly revoked by its issuer."

### ISSUE THREAD

**Issue by ScottVordem** [ericwj/PsSecDrv#9]
I have retried everything from the very beginning of the instructions twice now and I still get this error when running `sc start secdrv` at the very end.

```
[SC] StartService FAILED 2148204812:

A certificate was explicitly revoked by its issuer.

```

On latest version of Windows 11. I don't what I am doing wrong.

**Comment by ScottVordem** [comment]
Also, all instructions complete successfully in the terminal, there are no errors

**Comment by ericwj** [comment]
Double click the certificate in **certlm.msc** and see if it shows "_This certificate is OK._" under _Certificate Status_ on the tab _Certification path_ or does it look like [this](https://filestore.community.support.microsoft.com/api/images/37b3b1ce-1f3b-42e2-b686-6af8679908b7?upload=true&fud_access=wJJIheezUklbAN2ppeDns8cDNpYs3nCYjgitr%2bfFBh2dqlqMuW7np3F6Utp%2fKMltnRRYFtVjOMO5tpbpW9UyRAwvLeec5emAPixgq9ta07Dgnp2aq5eJbnfd%2fU3qhn5498QChOTHl3NpYS7xR7zASsaF20jo4ICSz2XTm%2b3GDR4XitSm7nHRR843ku7uXQ4oF6innoBxMaSe9UfrAdMi7owFKjdP9m1UP2W5KAtfQLOnziM%2fiduRhPveeHboObdmu0NLFtBa11hqtBtToCsba6Olq5zKS1RGfdvZ%2fHMfEYFlfIPhBB2A0WMs5YemjjqsGqAm3OP4yZ7p6PZhKSR7PjUGMK%2bPdkg2eYhND6DaLjBVYiLdnD7vPJFY4z5fXHYEkl5QPvMv8yi5HmvLBy5GZDJAB2Ljh2gzQmC%2by7M2rjI%3d)? In the latter case try to delete existing certificates for SECDRV from all stores mentioned in the readme, recreate a certificate and copy them again as per the readme.

Verify that you have the same status in the three stores where it should be located: Personal, Trusted Publishers and Trusted Root Certification Authorities afterwards. Nothing is OK except if you see "_This certificate is OK._" in three places.

Make sure you do that right because there is a folder "Untrusted Certificates" and it can get screwed up if anything gets in there which wasn't already before. I'm not sure it can hold plain certificates (intead of just CRLs), but having any SECDRV certificates there is certainly bad.

**Comment by ScottVordem** [comment]
All certificates say they are okay and are only in the three spots mentioned in the instructions.

Now I know that installing and running a game that uses it is technically the first step, but I got SECDRV.sys from [here](https://community.pcgamingwiki.com/files/file/1154-safedisc-driver-restoration-for-win10/) which includes the driver and registry entries then linked to here (your project) to follow instructions for `testsigning` and certificate creation. I tried that first and it didn't seem work.

I tried again the third time using a game that used it first, followed all the instructions again and insured that everything is in the right spot and working, including certificates.

upon reaching `sc.exe start secdrv` I still get the same error.

**Comment by ScottVordem** [comment]
Trying to launch the game changes the error to `This driver has been blocked from loading`

**Comment by ericwj** [comment]
Try scrapping that archive and the secdrv.sys that came with it. Inspect that .bat file to remove the registry settings it created. Virus check your system entirely with an up-to-date scanner like Microsoft Defender. Better yet pave your system and rebuild using original media.

The SECDRV.sys from that site claims to be the exact same version that you can download from this repo, but it is 5KB larger. It could be benign like ASCII art in a resource that this guy added. But you won't see it, so why then do it? Or it could be a trojan horse for pretty much any zomby. I can assure you that it is not legit and cannot be trusted.

Then try again using each and every instruction on this repo, including the download of the legit SECDRV.sys that I provided.

And then if it doesn't work, start being really careful to vet every byte on your harddrive. Like format zero erase your disk and reinstall Windows downloaded anew from the web. Or if you don't want to burn your ship behind you, bitlocker your existing partition, add a clean one but let Windows setup format it and never provide the bitlocker key to the new installation of windows.

**Comment by ericwj** [comment]
Since you have test signing on and secure boot disabled, special care must be taken to be 100% sure you recreate all partitions once you are ready to pave and reinstall. The volume boot record and master boot record on your disk aren't protected by secure boot, hence all of them can be infected, even though on my system that SECDRV.sys doesn't trigger Microsoft Defender. Whatever is in there could be new or unknown as of yet (a zero day). You must be sure you don't boot from these partitions, that you remove all partitions and recreate them from a Windows 10/11 CD that you burn or something. Or if you can't empty them good luck finding a way to overwrite the code in these sectors with some tool or whatnot and try not to loose the file system in the process. Usually the appropriate goodbye in this situation is 'have a good yesterday'. I'll make it hasta la vista babeh

**Comment by ericwj** [comment]
For my own record
[Microsoft Security Intelligence](https://www.microsoft.com/en-us/wdsi) | [Submission Details](https://www.microsoft.com/en-us/wdsi/submission/37b80d73-562d-4d22-8700-f1ee230d659c) (requires sign-in)

**Comment by ScottVordem** [comment]
Woah. I appreciate the concern but I don't think there is anything to worry about. The one you uploaded is dated September 2006 right?

The one on PcGamingWiki is dated newer, January 2012. Is says that on the "Date modified" in both Windows and 7zip. It could simply be just a newer version.

I will be taking your advice though and doing some of the things you mentioned.

My disks don't use MBR, they use GPT.

**Comment by ericwj** [comment]
No it isn't. It has the exact same date and version string but a different size.

Even GPT disks have VBR's.

Why in fact would you want to combine that SECDRV.sys and that batch file with the instructions here? These instructions are self sufficient.

**Comment by ScottVordem** [comment]
How do you know for sure it isn't just a newer version? Can you explain the process you did? 

I used that one because PcGamingWiki is a well known and a popular website to fix problems with old and modern games. That was a solution to the SafeDisk DRM problems on modern systems.

**Comment by ScottVordem** [comment]
I have alerted PcGamingWiki moderation of the possible fake file and are waiting a response from the uploader so they can explain themselves.

Do you know if Windows 11 itself has any methods to repair the GPT information without deleting data? I still want to do that as a precaution.

**Comment by ScottVordem** [comment]
PcGamingWiki examined the file. The SECDRC.SYS file there contains a code signing cert within the file, that's the extra 5KB. The uploader failed to mention that the SECDRV file was already self signed. It is harmless, and was identified as being identical to yours once the certificate code was removed.

**Comment by ScottVordem** [comment]
The file on PcGamingWiki has been updated to no longer include the certificate within SECDRV.SYS and now provides your SECDRV.SYS and a x86 version of it. I checked the 64-bit version's hash and it matches the one you provide. the 32-bit version is extracted from an MSDN ISO available from "My Visual Studio".

Since this Issue is now WAAY off topic, feel fee to close it and if I have any other issues i'll just create a new one.

Once again I appreciate your concern and happy to say there was no malicious intent, just lack of communication on the upload.

**Comment by ericwj** [comment]
> How do you know for sure it isn't just a newer version? Can you explain the process you did?

I checked the details tab. There is a 'Product Version' string amongst others with a version and a date in it. That whole string is exactly equal to the 'Product Version' in the SECDRV.sys that you can download here.

> I used that one because PcGamingWiki (...)

The site is well known. But it is a community upload. Anyone, with any intent, can upload files. So using it is not the right thing to do if you have a complete solution that does the exact same from start to finish. You have to scrutinize the sourcing of bits you put on your system permanently, thoroughly, completely. Even if you download cracks and the like, know the risk you take, shield what you cannot loose, make sure you can pave and rebuild if necessary.

> The SECDRC.SYS file there contains a code signing cert within the file, that's the extra 5KB.

OK. At the very least it is very sloppy to touch a file and redistribute it modified. And I can imagine the certificate in the executable frustrates the driver verification that Windows does.

> Do you know if Windows 11 itself has any methods to repair the GPT information (...)

I think you were right about GPT not having MBR's lying around. But replacing the VBR on individual partitions would require reformatting. If you're really savvy you can inspect the VBR and compare the segment of code in it with a well-known good one. If you're lucky that's all you need to do. If its different easiest is to empty the partition and reformat. Overwriting the VBR is inherently dangerous because you have to keep the data part of the VBR as it informs where the partition is and how it is formatted, etc.

> feel fee to close it

I assume you managed to get it installed and working?

**Comment by ScottVordem** [comment]
> I assume you managed to get it installed and working?

Yep! It works like it should now following your directions. The issue was the already bundled certificate within the other SECDRV file. Once that was gone, it works like it should!

**Comment by ScottVordem** [comment]
On an unrelated note, I figured out how to get this to work without disabling secure boot while still using built-in Windows resources, nothing third party.

Windows 11 (and 10) has an advanced startup feature. You can access it by either going to settings -> System ->Recovery and clicking "Restart Now" under "Advanced Startup", or by clicking the power button in the start menu and hold shift while clicking Restart.

From there, a screen comes up. Click on Troubleshoot -> Advanced Options -> Startup Settings and click restart in the bottom right corner.

After that, Another screen come up. Press "7" on the keyboard (Not Numpad) to disable Driver signature enforcement.

It does not put the text in the corner like testsigning does, but SECDRV does work this way also, all without disabling Secure Boot. Bit more restarting though.

The Driver signature enforcement re-enables itself after the next system reboot.

**Comment by ericwj** [comment]
Yeah some people might find that useful. I might add a remark about this to the readme. Thanks!
